In [1]:
import numpy as np

## How to create an array 

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [3]:
type(a)

numpy.ndarray

## Basic Operations of array

In [5]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [6]:
# creating a 2d array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [8]:
# creating a 3d array 
a3 = np.array([[[2,3,4],[7,8,9]],[[4,5,6],[10,11,12]]])
print(a3)

[[[ 2  3  4]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [17]:
# creating a 4d array
a4 = np.array([[[[1,2],[3,4]]
                ,[[5,6],[7,8]]]
                ,[[[9,10],[11,12]]
                  ,[[13,14],[15,16]]]])
print(a4)              

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


In [11]:
print(a2.shape)
print(a3.shape) # 2 2d arrays with 2 rows and 3 columns

(2, 3)
(2, 2, 3)


In [13]:
print(a2.ndim)
print(a3.ndim)

2
3


In [14]:
print(a2.dtype)

int64


In [18]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
np.random.randint(1,11, size = (3,5))

array([[ 5,  7, 10,  6,  2],
       [ 2,  4,  4,  1,  4],
       [ 3,  7,  9,  1,  3]], dtype=int32)